export categories = [
  { category: 'Best Picture' },
  { category: 'Actor in a Leading Role' },
  { category: 'Actress in a Leading Role' },
  { category: 'Actor in a Supporting Role' },
  { category: 'Animated Feature Film' },
  { category: 'Cinematography' },
  { category: 'Costume Design' },
  { category: 'Directing' },
  { category: 'Documentary (Feature)' },
  { category: 'Documentary (Short Subject)' },
  { category: 'Film Editing' },
  { category: 'Foreign Language Film' },
  { category: 'Makeup and Hairstyling' },
  { category: 'Music (Original Score)' },
  { category: 'Music (Original Song)' },
  { category: 'Production Design' },
  { category: 'Short Film (Animated)' },
  { category: 'Short Film (Live Action)' },
  { category: 'Sound Editing' },
  { category: 'Sound Mixing' },
  { category: 'Writing (Adapted Screenplay)' },
  { category: 'Writing (Original Screenplay)' },
];

// These are IMDB ids
const movies = {
  { id: '', name: 'Call Me by Your Name', image: '' },
  { id: 3, name: 'Darkest Hour', image: '' },
  { id: 4, name: 'Dunkirk', image: '' },
  { id: 5, name: 'Get Out', image: '' },
  { id: 6,  name: 'Lady Bird', image: '' },
  { id: 7, name: 'Phantom Thread', image: '' },
  { id: 8,  name: 'The Post', image: '' },
  { id: 'tt5580390',  name: 'The Shape of Water' },
  { id: 10, name: 'Three Billboards outside Ebbing, Missouri', image: '' },
}
